// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Job struct {
	ID        string  `json:"id"`
	Company   string  `json:"company"`
	Role      string  `json:"role"`
	Link      *string `json:"link"`
	Status    Status  `json:"status"`
	CreatedAt string  `json:"createdAt"`
}

type Mutation struct {
}

type Query struct {
}

type Status string

const (
	StatusApplied   Status = "APPLIED"
	StatusInterview Status = "INTERVIEW"
	StatusOffer     Status = "OFFER"
	StatusRejected  Status = "REJECTED"
)

type StatusCount struct {
	Status Status `json:"status"`
	Count  int    `json:"count"`
}
